[package]
name = "proofsargs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff = { version = "0.4", features = [ "asm" ] }
rand = { version = "0.8" }
sha2 = { version = "0.10.8" }